# Generated by Django 3.0.5 on 2020-05-01 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ded', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='name',
            new_name='title',
        ),
    ]
